const reviews=[
 {rating:2,text:'Submitted my documents four days ago and KYC is still pending.',theme:'KYC & Aadhaar',sentiment:'negative',date:'04 Sep 2026'},
 {rating:2,text:"Money was deducted but the deposit isn't showing in my account.",theme:'UPI & Payments',sentiment:'negative',date:'01 Sep 2026'},
 {rating:5,text:'Very easy to start investing. The whole process took just a few minutes.',theme:'Onboarding',sentiment:'positive',date:'22 Aug 2026'},
 {rating:2,text:'Charts freeze exactly when I need them most. Please fix the lag.',theme:'Performance',sentiment:'negative',date:'29 Aug 2026'},
 {rating:3,text:'The interface is simple, but my P&L takes too long to update.',theme:'Portfolio sync',sentiment:'mixed',date:'28 Aug 2026'},
 {rating:4,text:'Great app for mutual funds. Would love clearer status for withdrawals.',theme:'Withdrawals',sentiment:'mixed',date:'24 Aug 2026'}
];
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function showView(name){$$('.screen').forEach(el=>el.classList.toggle('active',el.id===name));$$('.nav').forEach(el=>el.classList.toggle('active',el.dataset.view===name));const label={dashboard:'Weekly Pulse',detail:'Pulse Detail View',reviews:'Review Explorer',integrations:'Pipeline Hub'}[name];$('#crumb-label').textContent=label;window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));$$('[data-target]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.target)));
function renderReviews(){const query=($('#search')?.value||'').toLowerCase();const sentiment=$('#sentiment')?.value||'all';const rating=$('#rating')?.value||'all';const filtered=reviews.filter(r=>(!query||r.text.toLowerCase().includes(query)||r.theme.toLowerCase().includes(query))&&(sentiment==='all'||r.sentiment===sentiment)&&(rating==='all'||String(r.rating)===rating));$('#review-rows').innerHTML=filtered.map((r,i)=>`<tr data-index="${reviews.indexOf(r)}"><td class="stars">${'★'.repeat(r.rating)}<span style="color:#dfe4eb">${'★'.repeat(5-r.rating)}</span></td><td class="review-copy">${r.text}</td><td><span class="tag">${r.theme}</span></td><td><span class="risk ${r.sentiment==='positive'?'watch':r.sentiment==='negative'?'critical':'high'}">${r.sentiment.toUpperCase()}</span></td><td>${r.date}</td><td>→</td></tr>`).join('')||'<tr><td colspan="6" style="text-align:center;padding:35px;color:#8792a1">No reviews match these filters.</td></tr>';$('#shown').textContent=filtered.length;$$('#review-rows tr[data-index]').forEach(row=>row.addEventListener('click',()=>openDrawer(reviews[row.dataset.index])))}
function openDrawer(r){$('#drawer-title').textContent=r.theme;$('#drawer-text').innerHTML=`“${r.text}”<small>${r.rating}★ · ${r.date} · anonymized</small>`;$('#drawer-rating').textContent=`${r.rating} / 5`;$('#drawer-theme').textContent=r.theme;$('#drawer-date').textContent=r.date;$('#drawer').classList.add('open')}
$('#close-drawer').addEventListener('click',()=>$('#drawer').classList.remove('open'));$('#drawer').addEventListener('click',e=>{if(e.target.id==='drawer')$('#drawer').classList.remove('open')});['search','sentiment','rating'].forEach(id=>$('#'+id).addEventListener('input',renderReviews));renderReviews();
$('#generate').addEventListener('click',()=>{const b=$('#generate');b.disabled=true;b.textContent='Generating…';toast('Pulse generation started. We will update this view when it is ready.');setTimeout(()=>{b.disabled=false;b.innerHTML='✦ Generate pulse';toast('Weekly pulse generated and ready for review.');},1800)});$('#run-pulse').addEventListener('click',()=>toast('Weekly pulse run queued through MCP.'));$('#deliver').addEventListener('click',()=>toast('Docs updated and Gmail draft created through MCP.'));$$('.outline').forEach(btn=>{if(btn.textContent.includes('Export'))btn.addEventListener('click',()=>toast('Export prepared from the current pulse.'))});
